import type { Metadata } from 'next';
import { NextIntlClientProvider, useMessages } from 'next-intl';

import Information from '@/components/shares/Information';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Shares() {
  const messages = useMessages();

  return (
    <NextIntlClientProvider messages={messages}>
      <Information />
    </NextIntlClientProvider>
  );
}
