import type { Metadata } from 'next';

import Information from '@/components/shares/Information';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Shares() {
  return <Information />;
}
