import type { Metadata } from 'next';
import { dehydrate, HydrationBoundary, QueryClient } from '@tanstack/react-query';

import { getCommunityShares } from '@/api/shares';
import Information from '@/components/shares/Information';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function Shares() {
  const queryClient = new QueryClient();

  // FIXME: dynamic key 처리
  await queryClient.prefetchQuery({
    queryKey: ['G0IZUDWCL'],
    queryFn: async () => getCommunityShares('G0IZUDWCL'),
  });

  return (
    <HydrationBoundary state={dehydrate(queryClient)}>
      <Information />
    </HydrationBoundary>
  );
}
